# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouplist',
            options={'default_permissions': [], 'ordering': ['appID', 'groupID']},
        ),
        migrations.RemoveField(
            model_name='grouplist',
            name='groupName',
        ),
        migrations.AddField(
            model_name='grouplist',
            name='appID',
            field=models.CharField(default='MOBILE', max_length=255),
        ),
        migrations.AddField(
            model_name='grouplist',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
