# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-05 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20170928_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplist',
            name='appID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.AppList'),
        ),
    ]
