# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20170423_1236'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grouplist',
            unique_together=set([('appID', 'groupID')]),
        ),
    ]
