# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20170423_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplist',
            name='groupID',
            field=models.CharField(max_length=255),
        ),
    ]
