# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginID', models.CharField(db_index=True, max_length=255, unique=True)),
                ('password', models.TextField()),
                ('token', models.TextField(null=True)),
                ('refresh_token', models.TextField(null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('createdAT', models.DateTimeField(auto_now_add=True)),
                ('updatedAT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auth',
                'ordering': ['loginID'],
                'default_permissions': [],
            },
        ),
    ]
