# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-28 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginID', models.CharField(db_index=True, max_length=255)),
                ('password', models.TextField()),
                ('appID', models.CharField(max_length=255)),
                ('deviceID', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('createdAT', models.DateTimeField(auto_now_add=True)),
                ('updatedAT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auth',
                'ordering': ['appID', 'loginID'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(null=True)),
                ('deviceID', models.TextField()),
                ('createdAT', models.DateTimeField(auto_now_add=True)),
                ('updatedAT', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_jwt.Auth')),
            ],
            options={
                'db_table': 'token',
                'ordering': ['user'],
                'default_permissions': [],
            },
        ),
        migrations.AlterUniqueTogether(
            name='auth',
            unique_together=set([('loginID', 'appID')]),
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set([('user', 'deviceID')]),
        ),
    ]
