# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-28 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_jwt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='appID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AppList'),
        ),
    ]
