# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_jwt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(null=True)),
                ('deviceID', models.CharField(default=None, max_length=255)),
                ('createdAT', models.DateTimeField(auto_now_add=True)),
                ('updatedAT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'token',
                'ordering': ['user'],
                'default_permissions': [],
            },
        ),
        migrations.RemoveField(
            model_name='auth',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='auth',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='auth',
            name='token',
        ),
        migrations.AddField(
            model_name='auth',
            name='appID',
            field=models.CharField(default='MOBILE', max_length=255),
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_jwt.Auth'),
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set([('user', 'deviceID')]),
        ),
    ]
