# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_jwt', '0002_auto_20170423_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='appID',
            field=models.CharField(max_length=255),
        ),
    ]
