# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_jwt', '0003_auto_20170423_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='deviceID',
            field=models.CharField(default='postman', max_length=255),
        ),
    ]
