# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-05 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_jwt', '0003_auto_20171004_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='deviceID',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='token',
            name='deviceID',
            field=models.TextField(db_index=True),
        ),
    ]
