# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-05 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_jwt', '0004_auto_20171005_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='appID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.AppList'),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_jwt.Auth'),
        ),
    ]
