# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_jwt', '0004_auth_deviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='loginID',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='auth',
            unique_together=set([('loginID', 'appID')]),
        ),
    ]
