# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-18 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170928_1242'),
        ('auth_jwt', '0005_auto_20171005_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField(null=True)),
                ('createdAT', models.DateTimeField(auto_now_add=True)),
                ('appID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.AppList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_jwt.Auth')),
            ],
            options={
                'db_table': 'activity',
                'ordering': ['user'],
                'default_permissions': [],
            },
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set([('user', 'service', 'appID', 'createdAT')]),
        ),
    ]
