# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_jwt', '0005_auto_20170424_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='deviceID',
            field=models.TextField(),
        ),
    ]
