# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-18 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_jwt', '0006_auto_20171018_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set([]),
        ),
    ]
