# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-18 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_jwt', '0008_auto_20171018_1255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
