# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-05 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('createdAT', models.DateTimeField(auto_now_add=True)),
                ('updatedAT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_domain',
                'ordering': ['domain'],
                'default_permissions': [],
            },
        ),
    ]
