# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelist',
            name='serviceName',
        ),
        migrations.AddField(
            model_name='servicelist',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='servicelist',
            name='moduleID',
            field=models.CharField(default='GRAPH', max_length=255),
        ),
    ]
