# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-08 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20171005_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelist',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
