# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20170423_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelist',
            name='moduleID',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='servicelist',
            unique_together=set([('moduleID', 'serviceID')]),
        ),
    ]
