# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-28 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applist',
            options={'default_permissions': [], 'ordering': ['appName']},
        ),
        migrations.RemoveField(
            model_name='applist',
            name='appID',
        ),
    ]
