# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-18 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, null=True)),
                ('service', models.TextField(null=True)),
                ('app', models.IntegerField(default=0)),
                ('createdAT', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity',
                'ordering': ['user'],
                'default_permissions': [],
            },
        ),
    ]
