# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-28 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_jwt', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAT', models.DateTimeField(auto_now_add=True)),
                ('updatedAT', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.GroupList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_jwt.Auth')),
            ],
            options={
                'db_table': 'user_group',
                'ordering': ['group', 'user'],
                'default_permissions': [],
            },
        ),
        migrations.AlterUniqueTogether(
            name='usergroup',
            unique_together=set([('group', 'user')]),
        ),
    ]
