# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-05 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acl',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='group.GroupList'),
        ),
        migrations.AlterField(
            model_name='acl',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.ServiceList'),
        ),
    ]
